### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "auth_test2@mail.com",
    "password": "password"
}

### Find User by Id
GET http://localhost:3000/auth/1


### Find All Users with email
GET http://localhost:3000/auth?email=test2@mail.com

### Delete User by Id
DELETE http://localhost:3000/auth/3

### Update User 
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "test2@mail.com"
}
