### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "somebody@mail.com",
    "password": "121212"
}

### Sign Out
POST http://localhost:3000/auth/signout 

### Login
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "cookie_test@mail.com",
    "password": "password12345"
}


### Sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "cookie_test@mail.com",
    "password": "password12345"
}

### Get current user info
GET http://localhost:3000/auth/active

### Find User by Id
GET http://localhost:3000/auth/2

### Find All Users
GET http://localhost:3000/auth

### Find All Users with email
GET http://localhost:3000/auth?email=test2@mail.com

### Delete User by Id
DELETE http://localhost:3000/auth/9

### Update User 
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "test2@mail.com"
}
